version: '3.5'

services:

  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./configs/mysql/database:/var/lib/mysql
      - ./configs/mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      rede:
        ipv4_address: 10.5.0.2

  app:
    container_name: ${APP_CONTAINER_NAME}
    build: .
    restart: unless-stopped
    depends_on: 
      - mysql
    volumes:
      - ./configs/jboss_wildfly:/opt/jboss/wildfly
    ports:
      - ${APP_PORT}:8081
      - ${APP_ADMIN_PORT}:9990
    networks:      
      rede:
        ipv4_address: 10.5.0.3

networks:
  rede:
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16